ml5js/ml5-website-v02-docsify

docs/README.md
fix next_step wrong link bug
TODO
get suggestions on the current structure & content
get suggestions for 'What Next?'
update style & layout
=> update next step link

docs/README.md
TODO
1. get suggestions on the current structure & content
2. get suggestions for 'What Next?'
3. update style & layout
=> fix syntax error

docs/css/style.css, docs/reference/pose-estimation.md
Experimented with various page structures and styles on Pose Estimation. Pushed for everyone to review.
=> update page structures and styles

docs/reference/iframes/pose-estimation/index.html, docs/reference/iframes/pose-estimation/main.html, docs/reference/iframes/pose-estimation/script.js, docs/reference/iframes/style.css
Add an iframe that provides interactivity and real-time demo.
=> upload files for iframe

docs/reference/iframes/pose-estimation/main.html, docs/reference/iframes/pose-estimation/script.js
=> modify the iframe example

docs/css/style.css, docs/reference/iframes/pose-estimation/index.html, docs/reference/iframes/pose-estimation/main.html, docs/reference/iframes/pose-estimation/script.js, docs/reference/iframes/style.css, docs/reference/pose-estimation.md, docs/sidebar.md
add Moon's pose estimation page
=> Quinn.getting started

docs/learning/ml5_glossary.md, docs/reference/handpose.md, docs/reference/iframes/handpose-keypoints/index.html, docs/reference/iframes/handpose-keypoints/main.html, docs/reference/iframes/handpose-keypoints/script.js
1. add glossary topic tabs
2. update handpose model page
=> Quinn.add topic tab

docs/README.md
Here some suggestions for reading through the Getting Started - please take the parts you find helpful, and ignore the rest!
=> Some suggestions for Getting Started

README.md
This is a minor change to the README file only, I am testing the netlify build process.
=> Testing Build Process

docs/README.md, docs/learning/ml5-glossary.md, docs/reference/bodypose.md, docs/reference/iframes/pose-estimation/index.html, docs/reference/iframes/pose-estimation/ready.html, docs/reference/iframes/pose-estimation/script.js, docs/welcome/next-steps.md
To-do
1. think about the order of `examples` vs `How to`
2. a bit more detailed work on `methods`
3. review the whole session wording again
=> Quinn rewrite bodypose content

docs/css/global.css, docs/css/style-markdown.css, docs/index.html
This PR is to add a footer and I also tried to change the behavior of the sidebar toggle to the right side when it is opened. In the previous version, the toggle will overlapped with the menu items. This is the preview:
@MOQN @QuinnHe @myrahsa  Please feel free to give me some feedback on this!
=> Added footer & changed sidebar toggle behavior

docs/css/global.css, docs/css/style-markdown.css
"warn" is used to emphasize tips.
=> update the styles for "warn"

docs/reference/bodypose.md
Added Dan's suggestions from #74 and shortened example code using the FaceMesh page as reference.
=> update bodypose example code and methods

docs/css/global.css, docs/css/style-markdown.css, docs/footer.md, docs/index.html
@alanvww Thank you so much for adding the footer! I organized it more and applied additional styles. I am not 100% satisfied with the look at this moment but let's try this way for a while and see how it could be improved. :D
=> update the content and styles of the footer

docs/css/style-markdown.css
Modify the tip (!>) style so that it can be used for code explanation.
=> Modify Tip's Style

docs/reference/body-segmentation.md, docs/reference/bodypose.md, docs/reference/facemesh.md, docs/reference/handpose.md, docs/reference/iframes/body-segmentation/script.js, docs/reference/iframes/facemesh-keypoints/script.js, docs/reference/iframes/handpose-keypoints/script.js, docs/reference/iframes/image-teachable-machine/script.js, docs/reference/iframes/pose-estimation/script.js, docs/reference/image-classifier-tm.md, docs/reference/image-classifier.md
We will use a fixed size for the webcam video. Also, unnecessary words and elements were removed.
=> Apply minor changes for script examples / Remove unncessary words and elements

docs/footer.md, docs/index.html
=> Update the links to ml5js.org

docs/reference/iframes/sound-classifier/index.html, docs/reference/iframes/sound-classifier/ready.html, docs/reference/iframes/sound-classifier/run.html, docs/reference/iframes/sound-classifier/script.js, docs/reference/sound-classifier.md
Let me know anything that needs to be changed @QuinnHe! The example links are empty right now because the model example is not yet in the p5 collection.
=> Update sound classifier

docs/contributing/how-to-contribute.md
Reworded the contribution page and added links to submission forms as we discussed at the meeting.
=> Update How To Contribute page

docs/welcome/FAQ.md
Reworded some content and added a question about older versions. 
@QuinnHe I'm assuming this isn't entirely what you meant by #89, so I think this requires a separate question that's more detailed. I'm using this space to first add links to the old documentation/website. As always, feel free to add or remove anything!
=> Reword and update FAQ

docs/css/style-markdown.css
=> Removed `margin-top: 16px;`

docs/reference/iframes/sound-classifier/index.html, docs/reference/iframes/sound-classifier/ready.html, docs/reference/sound-classifier.md
Switched the example links from GitHub to p5 editor. Also adjusted the language in the demo iframe.
=> Update sound classifier example links

docs/css/global.css, docs/index.html
Hello @MOQN @QuinnHe , this is the test version of the banner with dismiss button and responsive for mobile. The style is temporary. Let me know what you think!
=> Added banner for old reference doc

docs/css/global.css, docs/css/style-markdown.css, docs/index.html, docs/learn/ml5-glossary.md, docs/sidebar.md
- Hide banner in mobile view
- Make title text overflow into new line if it is too long
- Tried to move the sidebar over the banner when it is opened to ensure mobile experience, but failed :(
Added logic to fix behavior. Now if the link is internal, the tab will force reload to make sure the content is correct.
=> Added OG image, style & tab behavior fixes

docs/reference/iframes/sentiment/ready.html, docs/reference/sentiment.md
Re #153
Adjusted some parts to match with the updated example code @QuinnHe.
=> Update sentiment guide

docs/reference/body-segmentation.md, docs/reference/bodypose.md
Updating the documents to fix issue #149 and address the changes in https://github.com/ml5js/ml5-next-gen/commit/a88a3a1f7ef0950c216b1b00f7b149b063ce537e
=> Update BodySegmentation MaskType option from "body" to "person" & BodyPose docs clean up

docs/reference/bodypose.md, docs/reference/iframes/bodypose/index.html, docs/reference/iframes/bodypose/run.html, docs/reference/iframes/bodypose/script.js
=> Fixed MoveNet example to use the latest sketch

.github/ISSUE_TEMPLATE/config.yml
=> Added external link options in issue template 

docs/reference/bodypose.md
elaborate keypoints3D array and keypoint3D property based on tensorflow.js doc #181
=> update z coordinate doc

docs/reference/bodypose.md
remove property z to keypoint3D property #185
=> fix missing property

docs/reference/sentiment.md
Change the return value of sentiment.predict() from 'score' to 'confidence'. #184
=> fix wrong property

docs/reference/bodypose.md, docs/reference/image-classifier-tm.md, docs/reference/image-classifier.md, docs/reference/sentiment.md
Resolved #189 with BodyPose and ImageClassifier tutorial links in documents.
=> Added links for video tutorials

docs/contributing/develop-contributor-notes.md
Including the [changes that got added](https://github.com/ml5js/ml5-next-gen/blob/main/CONTRIBUTING.md) in August.
=> Update contributing page

docs/reference/facemesh.md
=> Fixed typo in FaceMesh

docs/reference/facemesh.md
#200 
update description of `refineLandmarks` to specify if the left and right iris key points are included
=> update refineLandmarks description
